package com.transfers.transfertracker.util.errors

enum class AuthError {
    ERROR_UNKNOWN,
    ERROR_INTERNET_CONNECTION,
    ERROR_EMAIL_ALREADY_EXIST,
    ERROR_USER_NOT_FOUND,
    ERROR_USER_PROFILE_NOT_FOUND,
    ERROR_LOCAL_CACHE_ISSUE,
    ERROR_INVALID_EMAIL,
    ERROR_INVALID_PASSWORD,
    ERROR_WRONG_PASSWORD,
    ERROR_INTERNAL_ERROR,
    ERROR_FORCE_LOGOUT,
    ERROR_INVALID_ARGUMENT,
    ERROR_INVALID_PHONE_NUMBER,

}

enum class FBError {
    ERROR_UNKNOWN,
    ERROR_INTERNET_CONNECTION,
    ERROR_INTERNAL_ERROR,
    ERROR_CLIENT_CLOSED,
    ERROR_CLIENT_CANCELED,
    ERROR_BACKEND_FAILURE,
    ERROR_INTERNAL_CODE
}

enum class NewsDataError {
    ERROR_UNKNOWN,
    ERROR_INTERNET_CONNECTION,
    ERROR_MISSING_PARAMETER,
    ERROR_UNAUTHORIZED,
    ERROR_RESTRICTED,
    ERROR_DUPLICATE_PARAMETER,
    ERROR_UNSUPPORTED_TYPE,
    ERROR_UNPROCESSABLE_ENTITY,
    ERROR_MAX_REQUEST,
    ERROR_BACKEND_FAILURE,
    ERROR_INTERNAL_ERROR
}