package com.transfers.transfertracker.model.errors

object AuthCodes {

    const val ERROR_EMAIL_ALREADY_EXIST = "ERROR_EMAIL_ALREADY_IN_USE"
    const val ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND"
    const val ERROR_INVALID_EMAIL = "ERROR_INVALID_EMAIL"
    const val ERROR_WRONG_PASSWORD = "ERROR_WRONG_PASSWORD"
    const val ERROR_INVALID_PASSWORD = "ERROR_INVALID_PASSWORD"
    const val ERROR_INTERNAL_ERROR = "ERROR_INTERNAL_ERROR"
    const val ERROR_INVALID_ARGUMENT = "ERROR_INVALID_ARGUMENT"
    const val ERROR_INVALID_PHONE_NUMBER = "ERROR_INVALID_PHONE_NUMBER"

}