package com.transfers.transfertracker.model.errors

enum class AuthError {
    ERROR_EMAIL_ALREADY_EXIST,
    ERROR_USER_NOT_FOUND,
    ERROR_USER_PROFILE_NOT_FOUND,
    ERROR_LOCAL_CACHE_ISSUE,
    ERROR_INVALID_EMAIL,
    ERROR_INVALID_PASSWORD,
    ERROR_WRONG_PASSWORD,
    ERROR_INTERNAL_ERROR,
    ERROR_FORCE_LOGOUT,
    ERROR_INVALID_ARGUMENT,
    ERROR_INVALID_PHONE_NUMBER,
    ERROR_INTERNET_CONNECTION,
    ERROR_UNKNOWN
}